[package]
name = "teleproj"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.5"
dirs = "6.0.0"